autonomous:
  approach:
    untilDistance: 40.0
    doneDistance: 40.0
    speed: 0.3
    centerProportional: .3636
    centerThreshold: 7.0
    doneIterations: 2.0
  orient:
    centerProportional: .25
    orientedProportional: -.00333
    centerThreshold: 15.0
    orientThreshold: 50.0
  blind:
    speed: .5
    moveBackCenter: 4000
    moveBack: 8000
    turnRight: 30.0 
    turnLeft: 30.0
    finalBack: 9931
