robot:
  driveTrain:
    motors:
      rightFront:
        port: 0
        reverse: true
      rightBack: 
        port: 1
        reverse: true
      leftFront: 
        port: 3
      leftBack: 
        port: 4
  vision:
    camera:
      port: 0
    relay:
      port: 0
  sensors:
    ultrasonic:
      port: 3
  rope:
    motor:
      port: 6
      reverse: true
  gear:
    solenoid:
      inPort: 0
      outPort: 1
  pneumatics:
    compressor:
      port: 0
